language:
  - c

os:
 - linux
# - osx

compiler:
 - gcc
# - clang

env:
  global:
    - FEATURES="enable-static-engine enable-ec_nistp_64_gcc_128 enable-gost enable-idea enable-md2 enable-rc5 enable-rfc3779 enable-ssl-trace enable-ssl2 enable-ssl3 enable-zlib experimental-jpake no-zlib-dynamic"

script:
  - (test $TRAVIS_OS_NAME != "osx" && ./config $FEATURES 1>/dev/null && make depend 1>/dev/null && make 1>/dev/null && make test)
  - (test $TRAVIS_OS_NAME == "osx" &&./Configure $FEATURES 1>/dev/null && make depend 1>/dev/null && make 1>/dev/null && make test)
# exit 0)

matrix:
  allow_failures:
    - os: osx